//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ControlWorks.UI.Console.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ControlWorks.UI.Console.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap greenlight2 {
            get {
                object obj = ResourceManager.GetObject("greenlight2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ToleranceMinus,TolerancePlus,CalibrationDate,OriginalSQYards,CoilWidth,CoilNumber,Date,ChangeNumber,RollNumber,Inspector1,BatchNumber1,MaterialType1,OvenPosition,MaterialThk,Length,Data
        ///-0.05,0.05,12/25/2015,12,25,75,6/12/2016,TestChangeNumber1,5,Inspector1,BatchNumber1,MaterialType1,13,0.052,22.55,&quot;0.047,0.055,0.049,0.049,0.043,0.057,0.048,0.049,0.044,0.048,0.051,0.049,0.047,0.051,0.046,0.057,0.051,0.043,0.057,0.046,0.048,0.055,0.051,0.049,0.054,0.048,0.057,0.041,0.058,0.046,0.048,0.054,0.046,0.053,0.048, [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TestData {
            get {
                return ResourceManager.GetString("TestData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date,Time,Material,Thickness,OrigSqYds,BatchNumber,RollNumber,ChangeNumber,CalDate,CoilWidth,CoilNumber,OvenPosition,TolPlus,TolMinus,Inspector,Length_good,Length_thkScrap,Length_thkReclass,Length_VS_blisters,Length_VS_contamination,Length_VS_gas,Length_VS_holes,Length_VS_lumps,Length_VS_paperBreaks,Length_VS_paperSplice,Length_VS_shiny,Length_VS_slitterDefects,Length_VS_tapeInCoil,Length_VS_wrinkles,Length_VS_width,Length_VS_other,Length_VS_salvageScrap,Variance,Comments,THK1,THK2,Station,Salvage Scrap Val [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TMSdata {
            get {
                return ResourceManager.GetString("TMSdata", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap trafficlight_green {
            get {
                object obj = ResourceManager.GetObject("trafficlight_green", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap trafficlight_red {
            get {
                object obj = ResourceManager.GetObject("trafficlight_red", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
